// 候補国リスト
export const COUNTRIES = [
  "オーストラリア",
  "カナダ",
  "アメリカ",
  "イギリス",
  "ニュージーランド",
  "シンガポール",
  "ドイツ",
  "フランス",
  "台湾",
  "タイ",
  "アイルランド",
  "オランダ",
  "韓国",
  "ポルトガル",
  "UAE",
] as const;

export type Country = (typeof COUNTRIES)[number];

// 国の基本情報
export const COUNTRY_INFO: Record<Country, {
  emoji: string;
  language: string;
  climate: string;
  currency: string;
  capital: string;
}> = {
  オーストラリア: { emoji: "🇦🇺", language: "英語", climate: "温暖〜暑い", currency: "AUD", capital: "キャンベラ" },
  カナダ: { emoji: "🇨🇦", language: "英語・フランス語", climate: "涼しい〜寒い", currency: "CAD", capital: "オタワ" },
  アメリカ: { emoji: "🇺🇸", language: "英語", climate: "地域により様々", currency: "USD", capital: "ワシントンD.C." },
  イギリス: { emoji: "🇬🇧", language: "英語", climate: "涼しい・雨が多い", currency: "GBP", capital: "ロンドン" },
  ニュージーランド: { emoji: "🇳🇿", language: "英語", climate: "温暖〜涼しい", currency: "NZD", capital: "ウェリントン" },
  シンガポール: { emoji: "🇸🇬", language: "英語・中国語他", climate: "常夏", currency: "SGD", capital: "シンガポール" },
  ドイツ: { emoji: "🇩🇪", language: "ドイツ語", climate: "涼しい・四季あり", currency: "EUR", capital: "ベルリン" },
  フランス: { emoji: "🇫🇷", language: "フランス語", climate: "四季あり", currency: "EUR", capital: "パリ" },
  台湾: { emoji: "🇹🇼", language: "中国語", climate: "暑い・四季あり", currency: "TWD", capital: "台北" },
  タイ: { emoji: "🇹🇭", language: "タイ語", climate: "常夏・熱帯", currency: "THB", capital: "バンコク" },
  アイルランド: { emoji: "🇮🇪", language: "英語", climate: "涼しい・雨が多い", currency: "EUR", capital: "ダブリン" },
  オランダ: { emoji: "🇳🇱", language: "オランダ語", climate: "涼しい", currency: "EUR", capital: "アムステルダム" },
  韓国: { emoji: "🇰🇷", language: "韓国語", climate: "四季あり", currency: "KRW", capital: "ソウル" },
  ポルトガル: { emoji: "🇵🇹", language: "ポルトガル語", climate: "温暖・晴れ多い", currency: "EUR", capital: "リスボン" },
  UAE: { emoji: "🇦🇪", language: "アラビア語・英語", climate: "常夏・砂漠", currency: "AED", capital: "アブダビ" },
};

// 診断の質問
export const QUESTIONS = [
  {
    id: 1,
    question: "海外での目的は何ですか？",
    key: "purpose",
    multiple: false,
    options: [
      { label: "🎓 留学・進学", value: "study" },
      { label: "✈️ ワーキングホリデー", value: "working_holiday" },
      { label: "💼 転職・就職", value: "work" },
      { label: "🚀 起業・フリーランス", value: "startup" },
    ],
  },
  {
    id: 2,
    question: "月々の予算はどのくらいですか？",
    key: "budget",
    multiple: false,
    options: [
      { label: "💸 〜15万円", value: "low" },
      { label: "💰 15〜25万円", value: "mid" },
      { label: "💎 25〜40万円", value: "high" },
      { label: "🤑 40万円以上", value: "very_high" },
    ],
  },
  {
    id: 3,
    question: "滞在期間はどのくらいを考えていますか？",
    key: "duration",
    multiple: false,
    options: [
      { label: "🗓️ 3ヶ月未満", value: "short" },
      { label: "📅 3ヶ月〜1年", value: "mid" },
      { label: "🗓️ 1〜3年", value: "long" },
      { label: "🌍 3年以上（長期移住）", value: "very_long" },
    ],
  },
  {
    id: 4,
    question: "気候の好みは？",
    key: "climate",
    multiple: false,
    options: [
      { label: "☀️ 暑いのが好き（常夏・熱帯系）", value: "hot" },
      { label: "🌸 四季がある方が好き", value: "four_seasons" },
      { label: "🌬️ 涼しい・寒い方が好き", value: "cool" },
      { label: "🌤️ 気候はあまり気にしない", value: "any" },
    ],
  },
  {
    id: 5,
    question: "言語環境の希望は？",
    key: "language",
    multiple: false,
    options: [
      { label: "🇬🇧 英語のみの環境が良い", value: "english_only" },
      { label: "🌍 英語＋現地語も学びたい", value: "english_plus" },
      { label: "🗣️ 英語以外の現地語を学びたい", value: "local_language" },
      { label: "🇯🇵 日本人コミュニティが多い環境が安心", value: "japanese_community" },
    ],
  },
  {
    id: 6,
    question: "どんな環境が好きですか？",
    key: "environment",
    multiple: false,
    options: [
      { label: "🏙️ 都市・都会的な生活が好き", value: "city" },
      { label: "🌿 自然・アウトドアが好き", value: "nature" },
      { label: "🏙️🌿 都市と自然どちらも楽しみたい", value: "both" },
      { label: "🤷 どちらでもいい", value: "any" },
    ],
  },
  {
    id: 7,
    question: "治安についてどう考えますか？",
    key: "safety",
    multiple: false,
    options: [
      { label: "🔒 治安の良さは絶対に譲れない", value: "very_important" },
      { label: "🛡️ ある程度治安が良ければOK", value: "moderate" },
      { label: "🌍 多少のリスクより刺激的な環境を選ぶ", value: "adventurous" },
    ],
  },
  {
    id: 8,
    question: "どんなアクティビティ・ライフスタイルが好きですか？（最大2つ）",
    key: "activities",
    multiple: true,
    maxSelect: 2,
    options: [
      { label: "🏄 アウトドア・スポーツ", value: "outdoor" },
      { label: "🎨 アート・カルチャー・歴史", value: "culture" },
      { label: "🎉 ナイトライフ・エンタメ・都市文化", value: "nightlife" },
      { label: "💻 スタートアップ・テック・ビジネス", value: "tech" },
      { label: "🧘 ウェルネス・スローライフ", value: "wellness" },
    ],
  },
  {
    id: 9,
    question: "食の文化についての希望は？",
    key: "food",
    multiple: false,
    options: [
      { label: "🍱 日本料理が身近にある", value: "japanese" },
      { label: "🌮 多国籍・なんでもある環境が好き", value: "international" },
      { label: "🥗 ヘルシー・オーガニック文化が好き", value: "healthy" },
      { label: "🤷 あまり気にしない", value: "any" },
    ],
  },
  {
    id: 10,
    question: "移住先を選ぶとき、一番重視することは？",
    key: "priority",
    multiple: false,
    options: [
      { label: "💰 予算・生活コスト", value: "budget" },
      { label: "🌤️ 気候", value: "climate" },
      { label: "🗣️ 言語環境", value: "language" },
      { label: "🏙️ 都市・自然のバランス", value: "environment" },
      { label: "🔒 治安", value: "safety" },
      { label: "🏄 アクティビティ", value: "activities" },
      { label: "🍱 食の文化", value: "food" },
    ],
  },
] as const;

// スコアリングテーブル
export const SCORES: Record<string, Record<Country, Record<string, number>>> = {
  purpose: {
    オーストラリア: { study: 3, working_holiday: 3, work: 2, startup: 2 },
    カナダ: { study: 3, working_holiday: 3, work: 2, startup: 2 },
    アメリカ: { study: 3, working_holiday: 0, work: 3, startup: 3 },
    イギリス: { study: 3, working_holiday: 0, work: 3, startup: 2 },
    ニュージーランド: { study: 2, working_holiday: 3, work: 1, startup: 1 },
    シンガポール: { study: 2, working_holiday: 0, work: 3, startup: 3 },
    ドイツ: { study: 2, working_holiday: 1, work: 3, startup: 2 },
    フランス: { study: 2, working_holiday: 1, work: 2, startup: 2 },
    台湾: { study: 2, working_holiday: 1, work: 2, startup: 2 },
    タイ: { study: 1, working_holiday: 2, work: 1, startup: 3 },
    アイルランド: { study: 2, working_holiday: 2, work: 2, startup: 2 },
    オランダ: { study: 2, working_holiday: 2, work: 3, startup: 3 },
    韓国: { study: 2, working_holiday: 1, work: 2, startup: 2 },
    ポルトガル: { study: 1, working_holiday: 2, work: 2, startup: 3 },
    UAE: { study: 1, working_holiday: 0, work: 3, startup: 3 },
  },
  budget: {
    オーストラリア: { low: 0, mid: 2, high: 3, very_high: 3 },
    カナダ: { low: 0, mid: 2, high: 3, very_high: 3 },
    アメリカ: { low: 0, mid: 1, high: 2, very_high: 3 },
    イギリス: { low: 0, mid: 1, high: 3, very_high: 3 },
    ニュージーランド: { low: 0, mid: 2, high: 3, very_high: 3 },
    シンガポール: { low: 0, mid: 1, high: 2, very_high: 3 },
    ドイツ: { low: 1, mid: 2, high: 3, very_high: 2 },
    フランス: { low: 1, mid: 2, high: 3, very_high: 2 },
    台湾: { low: 3, mid: 3, high: 2, very_high: 1 },
    タイ: { low: 3, mid: 3, high: 2, very_high: 1 },
    アイルランド: { low: 1, mid: 2, high: 3, very_high: 2 },
    オランダ: { low: 1, mid: 2, high: 3, very_high: 2 },
    韓国: { low: 2, mid: 3, high: 2, very_high: 1 },
    ポルトガル: { low: 3, mid: 3, high: 2, very_high: 1 },
    UAE: { low: 0, mid: 1, high: 2, very_high: 3 },
  },
  duration: {
    オーストラリア: { short: 2, mid: 3, long: 3, very_long: 2 },
    カナダ: { short: 2, mid: 3, long: 3, very_long: 2 },
    アメリカ: { short: 1, mid: 1, long: 2, very_long: 2 },
    イギリス: { short: 1, mid: 2, long: 2, very_long: 2 },
    ニュージーランド: { short: 2, mid: 3, long: 2, very_long: 2 },
    シンガポール: { short: 1, mid: 1, long: 2, very_long: 2 },
    ドイツ: { short: 1, mid: 2, long: 3, very_long: 3 },
    フランス: { short: 1, mid: 2, long: 2, very_long: 2 },
    台湾: { short: 3, mid: 2, long: 2, very_long: 2 },
    タイ: { short: 3, mid: 2, long: 2, very_long: 1 },
    アイルランド: { short: 2, mid: 3, long: 2, very_long: 2 },
    オランダ: { short: 1, mid: 2, long: 2, very_long: 2 },
    韓国: { short: 2, mid: 3, long: 2, very_long: 2 },
    ポルトガル: { short: 2, mid: 3, long: 3, very_long: 3 },
    UAE: { short: 1, mid: 1, long: 2, very_long: 2 },
  },
  climate: {
    オーストラリア: { hot: 3, four_seasons: 2, cool: 0, any: 2 },
    カナダ: { hot: 0, four_seasons: 2, cool: 3, any: 2 },
    アメリカ: { hot: 1, four_seasons: 3, cool: 1, any: 2 },
    イギリス: { hot: 0, four_seasons: 2, cool: 3, any: 2 },
    ニュージーランド: { hot: 1, four_seasons: 3, cool: 2, any: 2 },
    シンガポール: { hot: 3, four_seasons: 0, cool: 0, any: 2 },
    ドイツ: { hot: 0, four_seasons: 2, cool: 3, any: 2 },
    フランス: { hot: 1, four_seasons: 3, cool: 1, any: 2 },
    台湾: { hot: 2, four_seasons: 2, cool: 0, any: 2 },
    タイ: { hot: 3, four_seasons: 0, cool: 0, any: 2 },
    アイルランド: { hot: 0, four_seasons: 1, cool: 3, any: 2 },
    オランダ: { hot: 0, four_seasons: 2, cool: 3, any: 2 },
    韓国: { hot: 1, four_seasons: 3, cool: 1, any: 2 },
    ポルトガル: { hot: 3, four_seasons: 2, cool: 0, any: 2 },
    UAE: { hot: 3, four_seasons: 0, cool: 0, any: 2 },
  },
  language: {
    オーストラリア: { english_only: 3, english_plus: 1, local_language: 0, japanese_community: 3 },
    カナダ: { english_only: 3, english_plus: 1, local_language: 0, japanese_community: 3 },
    アメリカ: { english_only: 3, english_plus: 1, local_language: 0, japanese_community: 3 },
    イギリス: { english_only: 3, english_plus: 1, local_language: 0, japanese_community: 1 },
    ニュージーランド: { english_only: 3, english_plus: 1, local_language: 0, japanese_community: 2 },
    シンガポール: { english_only: 2, english_plus: 3, local_language: 1, japanese_community: 2 },
    ドイツ: { english_only: 1, english_plus: 2, local_language: 3, japanese_community: 1 },
    フランス: { english_only: 1, english_plus: 2, local_language: 3, japanese_community: 1 },
    台湾: { english_only: 1, english_plus: 2, local_language: 3, japanese_community: 3 },
    タイ: { english_only: 1, english_plus: 2, local_language: 3, japanese_community: 3 },
    アイルランド: { english_only: 3, english_plus: 1, local_language: 0, japanese_community: 1 },
    オランダ: { english_only: 2, english_plus: 3, local_language: 2, japanese_community: 1 },
    韓国: { english_only: 1, english_plus: 2, local_language: 3, japanese_community: 2 },
    ポルトガル: { english_only: 1, english_plus: 2, local_language: 3, japanese_community: 1 },
    UAE: { english_only: 2, english_plus: 3, local_language: 1, japanese_community: 1 },
  },
  environment: {
    オーストラリア: { city: 2, nature: 3, both: 3, any: 2 },
    カナダ: { city: 2, nature: 3, both: 3, any: 2 },
    アメリカ: { city: 3, nature: 3, both: 3, any: 2 },
    イギリス: { city: 3, nature: 1, both: 2, any: 2 },
    ニュージーランド: { city: 1, nature: 3, both: 3, any: 2 },
    シンガポール: { city: 3, nature: 0, both: 1, any: 2 },
    ドイツ: { city: 3, nature: 2, both: 3, any: 2 },
    フランス: { city: 3, nature: 2, both: 3, any: 2 },
    台湾: { city: 2, nature: 2, both: 3, any: 2 },
    タイ: { city: 2, nature: 2, both: 3, any: 2 },
    アイルランド: { city: 2, nature: 3, both: 3, any: 2 },
    オランダ: { city: 3, nature: 1, both: 2, any: 2 },
    韓国: { city: 3, nature: 1, both: 2, any: 2 },
    ポルトガル: { city: 2, nature: 2, both: 3, any: 2 },
    UAE: { city: 3, nature: 0, both: 1, any: 2 },
  },
  safety: {
    オーストラリア: { very_important: 3, moderate: 3, adventurous: 2 },
    カナダ: { very_important: 2, moderate: 3, adventurous: 2 },
    アメリカ: { very_important: 1, moderate: 2, adventurous: 3 },
    イギリス: { very_important: 2, moderate: 3, adventurous: 2 },
    ニュージーランド: { very_important: 3, moderate: 3, adventurous: 2 },
    シンガポール: { very_important: 3, moderate: 3, adventurous: 1 },
    ドイツ: { very_important: 3, moderate: 3, adventurous: 2 },
    フランス: { very_important: 2, moderate: 3, adventurous: 2 },
    台湾: { very_important: 3, moderate: 3, adventurous: 2 },
    タイ: { very_important: 2, moderate: 3, adventurous: 2 },
    アイルランド: { very_important: 3, moderate: 3, adventurous: 2 },
    オランダ: { very_important: 3, moderate: 3, adventurous: 2 },
    韓国: { very_important: 2, moderate: 3, adventurous: 2 },
    ポルトガル: { very_important: 2, moderate: 3, adventurous: 2 },
    UAE: { very_important: 3, moderate: 3, adventurous: 1 },
  },
  activities: {
    オーストラリア: { outdoor: 3, culture: 2, nightlife: 2, tech: 2, wellness: 2 },
    カナダ: { outdoor: 3, culture: 2, nightlife: 2, tech: 3, wellness: 2 },
    アメリカ: { outdoor: 3, culture: 3, nightlife: 3, tech: 3, wellness: 2 },
    イギリス: { outdoor: 1, culture: 3, nightlife: 3, tech: 3, wellness: 1 },
    ニュージーランド: { outdoor: 3, culture: 2, nightlife: 1, tech: 1, wellness: 3 },
    シンガポール: { outdoor: 1, culture: 2, nightlife: 3, tech: 3, wellness: 1 },
    ドイツ: { outdoor: 1, culture: 3, nightlife: 3, tech: 3, wellness: 2 },
    フランス: { outdoor: 1, culture: 3, nightlife: 3, tech: 2, wellness: 2 },
    台湾: { outdoor: 2, culture: 3, nightlife: 2, tech: 2, wellness: 2 },
    タイ: { outdoor: 2, culture: 2, nightlife: 3, tech: 1, wellness: 3 },
    アイルランド: { outdoor: 2, culture: 3, nightlife: 2, tech: 1, wellness: 2 },
    オランダ: { outdoor: 1, culture: 3, nightlife: 3, tech: 3, wellness: 2 },
    韓国: { outdoor: 1, culture: 3, nightlife: 3, tech: 2, wellness: 1 },
    ポルトガル: { outdoor: 2, culture: 3, nightlife: 2, tech: 2, wellness: 3 },
    UAE: { outdoor: 1, culture: 2, nightlife: 3, tech: 3, wellness: 1 },
  },
  food: {
    オーストラリア: { japanese: 3, international: 3, healthy: 3, any: 2 },
    カナダ: { japanese: 3, international: 3, healthy: 3, any: 2 },
    アメリカ: { japanese: 3, international: 3, healthy: 2, any: 2 },
    イギリス: { japanese: 2, international: 3, healthy: 2, any: 2 },
    ニュージーランド: { japanese: 2, international: 2, healthy: 3, any: 2 },
    シンガポール: { japanese: 3, international: 3, healthy: 2, any: 2 },
    ドイツ: { japanese: 1, international: 2, healthy: 3, any: 2 },
    フランス: { japanese: 1, international: 2, healthy: 2, any: 2 },
    台湾: { japanese: 3, international: 2, healthy: 2, any: 2 },
    タイ: { japanese: 2, international: 2, healthy: 2, any: 2 },
    アイルランド: { japanese: 1, international: 2, healthy: 2, any: 2 },
    オランダ: { japanese: 2, international: 3, healthy: 2, any: 2 },
    韓国: { japanese: 2, international: 2, healthy: 2, any: 2 },
    ポルトガル: { japanese: 1, international: 2, healthy: 2, any: 2 },
    UAE: { japanese: 2, international: 3, healthy: 1, any: 2 },
  },
};

// 国名（日本語）→ Supabase slug マッピング
export const COUNTRY_SLUG: Record<Country, string> = {
  オーストラリア: "australia",
  カナダ: "canada",
  アメリカ: "usa",
  イギリス: "uk",
  ニュージーランド: "new-zealand",
  シンガポール: "singapore",
  ドイツ: "germany",
  フランス: "france",
  台湾: "taiwan",
  タイ: "thailand",
  アイルランド: "ireland",
  オランダ: "netherlands",
  韓国: "korea",
  ポルトガル: "portugal",
  UAE: "uae",
};

// 重み付けの対応マップ（Q10の選択肢 → 対応するスコアキー）
export const PRIORITY_MAP: Record<string, string> = {
  budget: "budget",
  climate: "climate",
  language: "language",
  environment: "environment",
  safety: "safety",
  activities: "activities",
  food: "food",
};
